// <auto-generated />
using Kemenkeu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kemenkeu.Migrations
{
    [DbContext(typeof(KemenkeuContext))]
    [Migration("20190521123718_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kemenkeu.Models.Pjpk", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("PJPK");
                });

            modelBuilder.Entity("Kemenkeu.Models.Proyek", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("DetailProyek")
                        .IsRequired()
                        .HasColumnName("Detail_Proyek")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaProyek")
                        .IsRequired()
                        .HasColumnName("Nama_Proyek")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("NilaiProyek")
                        .HasColumnName("Nilai_Proyek");

                    b.Property<string>("Provinsi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Sektor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("StatusProyek")
                        .IsRequired()
                        .HasColumnName("Status_Proyek")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Proyek");
                });
#pragma warning restore 612, 618
        }
    }
}
